-- Run this once in Supabase SQL Editor.
-- Academic data tables for student assignments, attendance and discussions.

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  title text not null,
  description text,
  due_date date,
  total_marks integer default 0,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz default now()
);

create table if not exists public.assignment_submissions (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  submission_url text,
  submitted_at timestamptz,
  marks numeric,
  feedback text,
  status text not null default 'pending' check (status in ('pending','submitted','graded','late')),
  unique(assignment_id, student_id)
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  attendance_date date not null,
  status text not null check (status in ('present','absent','late','excused')),
  subject text,
  created_at timestamptz default now(),
  unique(class_id, student_id, attendance_date, subject)
);

create table if not exists public.discussions (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  body text not null,
  created_at timestamptz default now()
);

create table if not exists public.discussion_replies (
  id bigint generated by default as identity primary key,
  discussion_id bigint not null references public.discussions(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz default now()
);

alter table public.assignments enable row level security;
alter table public.assignment_submissions enable row level security;
alter table public.attendance enable row level security;
alter table public.discussions enable row level security;
alter table public.discussion_replies enable row level security;

-- Students can read academic data for their assigned class.
drop policy if exists "students read class assignments" on public.assignments;
create policy "students read class assignments" on public.assignments for select to authenticated using (
  exists (select 1 from public.class_members cm where cm.class_id = assignments.class_id and cm.user_id = auth.uid())
  or public.is_admin()
);

drop policy if exists "students read own submissions" on public.assignment_submissions;
create policy "students read own submissions" on public.assignment_submissions for select to authenticated using (student_id = auth.uid() or public.is_admin());

drop policy if exists "students create own submissions" on public.assignment_submissions;
create policy "students create own submissions" on public.assignment_submissions for insert to authenticated with check (student_id = auth.uid());

drop policy if exists "students update own submissions" on public.assignment_submissions;
create policy "students update own submissions" on public.assignment_submissions for update to authenticated using (student_id = auth.uid() or public.is_admin()) with check (student_id = auth.uid() or public.is_admin());

drop policy if exists "students read own attendance" on public.attendance;
create policy "students read own attendance" on public.attendance for select to authenticated using (student_id = auth.uid() or public.is_admin());

drop policy if exists "class members read discussions" on public.discussions;
create policy "class members read discussions" on public.discussions for select to authenticated using (
  exists (select 1 from public.class_members cm where cm.class_id = discussions.class_id and cm.user_id = auth.uid())
  or public.is_admin()
);

drop policy if exists "class members create discussions" on public.discussions;
create policy "class members create discussions" on public.discussions for insert to authenticated with check (
  author_id = auth.uid() and exists (select 1 from public.class_members cm where cm.class_id = discussions.class_id and cm.user_id = auth.uid())
);

drop policy if exists "class members read replies" on public.discussion_replies;
create policy "class members read replies" on public.discussion_replies for select to authenticated using (
  exists (select 1 from public.discussions d join public.class_members cm on cm.class_id = d.class_id where d.id = discussion_replies.discussion_id and cm.user_id = auth.uid())
  or public.is_admin()
);

drop policy if exists "class members create replies" on public.discussion_replies;
create policy "class members create replies" on public.discussion_replies for insert to authenticated with check (
  author_id = auth.uid() and exists (select 1 from public.discussions d join public.class_members cm on cm.class_id = d.class_id where d.id = discussion_replies.discussion_id and cm.user_id = auth.uid())
);

create index if not exists assignments_class_id_idx on public.assignments(class_id);
create index if not exists attendance_student_id_idx on public.attendance(student_id);
create index if not exists discussions_class_id_idx on public.discussions(class_id);
