(function(){
'use strict';
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const date=v=>v?new Date(v).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}):'No due date';
async function context(){const db=window.mcmDb;if(!db)return null;const profile=await db.profile();if(!profile)return null;const ms=await db.members();const m=ms[0];return {profile,m,classId:m?.class_id};}
function shell(title,kicker,body){const old=document.querySelector('.student-app-shell');if(old){const main=old.querySelector('.student-main-area');if(main){main.innerHTML=`<header class="student-topbar"><button class="student-menu-toggle" aria-label="Open navigation">☰</button><div class="student-mobile-brand"><span class="student-brand-mark">◆</span><strong>UniConnect</strong></div><div class="student-search">Search courses, notes, discussions...</div><div class="student-user"><span class="student-user-avatar">D</span><span><strong>Student</strong><small>Student</small></span></div></header><section class="student-dashboard-content academic-page"><div class="student-dashboard-hero"><div><p class="student-label">MY CLASS MATTERS · STUDENT PORTAL</p><h1>${title}</h1><p>${kicker}</p></div></div>${body}</section>`;return main;}}return null;}
async function assignmentsPage(){try{const c=await context();if(!c)return;const rows=await window.mcmDb.assignments(c.classId);const body=rows.length?`<div class="academic-list">${rows.map(a=>`<article class="academic-card"><div><span class="academic-kicker">${esc(a.total_marks||0)} marks</span><h3>${esc(a.title)}</h3><p>${esc(a.description||'No description provided.')}</p></div><div class="academic-meta"><span>Due: ${esc(date(a.due_date))}</span><b>${esc(a.assignment_submissions?.[0]?.status||'pending')}</b></div></article>`).join('')}</div>`:`<div class="student-empty-state">No assignments have been published for your class yet.</div>`;shell('Assignments','Track your class assignments and submission deadlines.',body);}catch(e){console.warn(e)}}
async function discussionsPage(){try{const c=await context();if(!c)return;const rows=await window.mcmDb.discussions(c.classId);const body=rows.length?`<div class="academic-list">${rows.map(d=>`<article class="academic-card discussion-live-card"><div class="student-discussion-avatar">${esc((d.profiles?.full_name||'S')[0])}</div><div><span class="academic-kicker">${esc(d.profiles?.full_name||'Student')} · ${esc(date(d.created_at))}</span><h3>${esc(d.title)}</h3><p>${esc(d.body)}</p><small>${d.discussion_replies?.length||0} replies</small></div></article>`).join('')}</div>`:`<div class="student-empty-state">No discussions have been started in your class yet.</div>`;shell('Discussions','Ask questions, share ideas, and learn with your assigned class.',body);}catch(e){console.warn(e)}}
async function dashboardAcademic(){try{const c=await context();if(!c)return;const [assignments,attendance]=await Promise.all([window.mcmDb.assignments(c.classId),window.mcmDb.attendance(c.profile.id)]);const assignmentPanel=document.querySelector('.assignments-panel');if(assignmentPanel){const list=assignments.slice(0,3).map(a=>`<a class="resource-item" href="#assignments"><span class="file-icon pdf">TASK</span><span><strong>${esc(a.title)}</strong><small>Due ${esc(date(a.due_date))}</small></span><b>→</b></a>`).join('');assignmentPanel.innerHTML=`<div class="panel-heading"><div><p class="panel-kicker">ASSIGNMENTS</p><h2>Upcoming assignments</h2></div><a href="#assignments">See all →</a></div>${list||'<div class="student-empty-state">No assignments have been published yet.</div>'}`;}const progress=document.querySelector('.progress-panel');if(progress){const total=attendance.length,present=attendance.filter(x=>x.status==='present').length,percent=total?Math.round(present/total*100):null;progress.innerHTML=`<div class="panel-heading"><div><p class="panel-kicker">YOUR PROGRESS</p><h2>Attendance overview</h2></div><a href="#attendance">View details →</a></div><div class="academic-attendance-value">${percent===null?'—':percent+'%'}<small>${total?`${present} of ${total} classes attended`:'No attendance records yet'}</small></div>`;const stat=document.querySelector('.student-stat-card:nth-child(4) strong');if(stat)stat.textContent=percent===null?'Not available':percent+'%';}}catch(e){console.warn('Academic dashboard data failed',e)}}
function route(){const h=location.hash;if(h==='#assignments'){setTimeout(assignmentsPage,150)}else if(h==='#discussions'){setTimeout(discussionsPage,150)}else if(h===''||h==='#home'||h==='#student-dashboard'){setTimeout(dashboardAcademic,500)}}
window.addEventListener('hashchange',route);setTimeout(route,700);
})();
