(function(){
const key='mcmPortalData';
function data(){if(!window.portalData)window.portalData={classes:[],svls:[],students:[]};const saved=localStorage.getItem(key);if(saved)try{window.portalData=JSON.parse(saved)}catch(e){}return window.portalData}
function save(){localStorage.setItem(key,JSON.stringify(window.portalData))}
function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
function options(list,value,empty){return `<option value="">${empty}</option>`+list.map(x=>`<option value="${esc(x.name||x.className)}" ${String(x.name||x.className)===String(value)?'selected':''}>${esc(x.name||x.className)}</option>`).join('')}
window.adminPage=function(){const d=data();return `<div class="admin-wrap"><div class="admin-hero"><div><p class="eyebrow">University administration</p><h1>Management Center</h1><p class="muted">Manage classes, SVLs, students and portal access.</p></div><div class="admin-hero-actions"><button class="admin-btn" onclick="adminAdd()">+ Add Record</button></div></div><div class="admin-grid"><div class="admin-stat"><span class="muted">Classes</span><strong>${d.classes.length}</strong></div><div class="admin-stat"><span class="muted">SVLs</span><strong>${d.svls.length}</strong></div><div class="admin-stat"><span class="muted">Students</span><strong>${d.students.length}</strong></div><div class="admin-stat"><span class="muted">Accounts</span><strong>${d.svls.length+d.students.length}</strong></div></div><div class="admin-card"><div class="admin-tabs"><button class="admin-tab active" onclick="adminTab('classes',this)">Classes</button><button class="admin-tab" onclick="adminTab('svls',this)">SVLs</button><button class="admin-tab" onclick="adminTab('students',this)">Students</button></div><div id="admin-table-area">${adminTable('classes')}</div></div></div>`}
window.adminTable=function(type){const d=data()[type]||[];if(!d.length)return '<div class="admin-empty">No records found.</div>';const heads=type==='classes'?['ID','Class','SVL','Students','Status','Action']:type==='svls'?['ID','Name','Email','Class','Action']:['ID','Name','Email','Class','SVL','Action'];return `<div class="admin-table-scroll"><table class="admin-table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${d.map(x=>{const vals=type==='classes'?[x.id,x.name,x.svl,x.students,x.status]:type==='svls'?[x.id,x.name,x.email,x.className]:[x.id,x.name,x.email,x.className,x.svl];return `<tr>${vals.map(v=>`<td>${esc(v)}</td>`).join('')}<td><button class="admin-btn secondary" onclick="adminEdit('${type}','${x.id}')">Edit</button><button class="admin-btn danger" onclick="adminDelete('${type}','${x.id}')">Delete</button></td></tr>`}).join('')}</tbody></table></div>`}
window.adminTab=function(type,b){document.querySelectorAll('.admin-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#admin-table-area').innerHTML=adminTable(type)}
window.adminAdd=function(){adminForm('classes')}
window.adminForm=function(type,id){const d=data(),old=id?d[type].find(x=>x.id===id):{};const title=id?'Edit':'Add';let html='';if(type==='classes')html=`<label>Class name<input id="adm-name" value="${esc(old.name)}" placeholder="Class name"></label><label>Assigned SVL<input id="adm-svl" value="${esc(old.svl)}" placeholder="Assigned SVL"></label><label>Student count<input id="adm-students" value="${esc(old.students||0)}" type="number"></label><label>Status<select id="adm-status"><option>Active</option><option>Inactive</option></select></label>`;if(type==='svls')html=`<label>Full name<input id="adm-name" value="${esc(old.name)}" placeholder="Full name"></label><label>Login email/username<input id="adm-email" value="${esc(old.email)}" placeholder="svl@university.edu"></label><label>Temporary password<input id="adm-password" value="${esc(old.password)}" placeholder="Temporary password"></label><label>Assigned class<select id="adm-className">${options(d.classes,old.className,'Select class')}</select></label>`;if(type==='students')html=`<label>Full name<input id="adm-name" value="${esc(old.name)}" placeholder="Full name"></label><label>Login email/username<input id="adm-email" value="${esc(old.email)}" placeholder="student@university.edu"></label><label>Temporary password<input id="adm-password" value="${esc(old.password)}" placeholder="Temporary password"></label><label>Select class<select id="adm-className" onchange="adminStudentClassChanged()">${options(d.classes,old.className,'Select class')}</select></label><label>Assigned SVL<select id="adm-svl">${options(d.svls.filter(s=>!old.className||s.className===old.className),old.svl,'Select class first')}</select></label>`;const modal=document.createElement('div');modal.className='admin-modal';modal.innerHTML=`<div class="admin-modal-box"><button class="admin-modal-close" onclick="this.closest('.admin-modal').remove()">×</button><h2>${title} ${type.slice(0,-1)}</h2><div class="admin-form">${html}</div><button class="admin-btn" onclick="adminSave('${type}','${id||''}',this)">Save record</button></div>`;document.body.appendChild(modal)}
window.adminStudentClassChanged=function(){const d=data(),cls=document.querySelector('#adm-className').value,sel=document.querySelector('#adm-svl');sel.innerHTML=options(d.svls.filter(s=>s.className===cls),'','Select SVL for this class')}
window.adminSave=function(type,id,btn){const d=data(),fields=type==='classes'?['name','svl','students','status']:['name','email','password','className','svl'];const obj={};fields.forEach(k=>{const el=document.querySelector('#adm-'+k);obj[k]=el?el.value.trim():''});if(!obj.name||(!obj.email&&type!=='classes')||(type==='students'&&(!obj.className||!obj.svl))){alert('Please fill all required fields.');return}if(id)Object.assign(d[type].find(x=>x.id===id),obj);else{obj.id=(type==='classes'?'CLS-':type==='svls'?'SVL-':'STU-')+String(d[type].length+1).padStart(3,'0');if(type==='classes'&&!obj.students)obj.students=0;if(type==='classes'&&!obj.status)obj.status='Active';d[type].push(obj)}save();btn.closest('.admin-modal').remove();renderAdminRoute()}
window.adminEdit=function(type,id){adminForm(type,id)};window.adminDelete=function(type,id){if(confirm('Delete this record?')){window.portalData[type]=data()[type].filter(x=>x.id!==id);save();renderAdminRoute()}};window.renderAdminRoute=function(){if(location.hash.replace('#','')==='admin')document.querySelector('#app').innerHTML=adminPage()};window.addEventListener('hashchange',renderAdminRoute);if(location.hash.replace('#','')==='admin')renderAdminRoute()})();