(() => {
  const assignments = [
    {id:1,title:'Database Design Project',course:'Database Systems',due:'Sep 10, 2026',status:'pending',points:'20 marks',description:'Design a normalized database and submit the ERD with a short explanation.'},
    {id:2,title:'Marketing Case Study',course:'Marketing Management',due:'Sep 13, 2026',status:'progress',points:'15 marks',description:'Analyze the assigned case study and upload your recommendations.'},
    {id:3,title:'UI/UX Prototype',course:'Human Computer Interaction',due:'Sep 18, 2026',status:'pending',points:'25 marks',description:'Create a responsive prototype for the university student portal.'},
    {id:4,title:'Research Methodology Quiz',course:'Research Methods',due:'Completed',status:'completed',points:'10 marks',description:'Online quiz covering research design and data collection methods.'}
  ];
  const statusLabel={pending:'Pending','progress':'In Progress',completed:'Completed'};
  const app=()=>document.getElementById('app');
  function shell(content){return `<div class="app-shell"><aside class="sidebar"><div class="brand">Uni<span>Connect</span></div><nav><a href="#">Dashboard</a><a href="#courses">Courses</a><a href="#notes">Notes</a><a href="#discussions">Discussions</a><a class="active" href="#assignments">Assignments</a><a href="#timetable">Timetable</a><a href="#notifications">Notifications</a></nav></aside><main class="main-content"><header class="topbar"><div><span class="eyebrow">Student workspace</span><h2>Assignments</h2></div><div class="profile-chip">DR</div></header>${content}</main></div>`}
  function card(a){return `<article class="assignment-card"><div><h3>${a.title}</h3><div class="assignment-meta"><span>${a.course}</span><span>Due: ${a.due}</span><span>${a.points}</span></div></div><div class="assignment-side"><span class="assignment-status status-${a.status}">${statusLabel[a.status]}</span><div class="assignment-actions"><button class="secondary" data-view="${a.id}">Details</button>${a.status!=='completed'?`<button class="primary" data-submit="${a.id}">Submit</button>`:''}</div></div></article>`}
  function render(){if(location.hash!=='#assignments')return;app().innerHTML=shell(`<section class="assignments-page"><div class="assignments-head"><div><h1>Assignments</h1><p>Keep track of your coursework and upcoming deadlines.</p></div></div><div class="assignment-summary"><div class="assignment-stat"><span>Total assignments</span><strong>4</strong></div><div class="assignment-stat"><span>Pending</span><strong>2</strong></div><div class="assignment-stat"><span>In progress</span><strong>1</strong></div><div class="assignment-stat"><span>Completed</span><strong>1</strong></div></div><div class="assignment-tools"><input id="assignmentSearch" placeholder="Search assignments..."/><select id="assignmentStatus"><option value="all">All statuses</option><option value="pending">Pending</option><option value="progress">In Progress</option><option value="completed">Completed</option></select></div><div class="assignment-list" id="assignmentList">${assignments.map(card).join('')}</div></section>`);bind()}
  function bind(){const list=document.getElementById('assignmentList');const filter=()=>{const q=document.getElementById('assignmentSearch').value.toLowerCase();const s=document.getElementById('assignmentStatus').value;list.innerHTML=assignments.filter(a=>(s==='all'||a.status===s)&&(a.title+a.course).toLowerCase().includes(q)).map(card).join('')||'<p class="empty-state">No assignments found.</p>';bindButtons()};document.getElementById('assignmentSearch').oninput=filter;document.getElementById('assignmentStatus').onchange=filter;bindButtons()}
  function bindButtons(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const a=assignments.find(x=>x.id==b.dataset.view);alert(`${a.title}\n\n${a.description}\n\nDue: ${a.due}`)});document.querySelectorAll('[data-submit]').forEach(b=>b.onclick=()=>alert('Submission area is ready for backend integration.'))}
  window.addEventListener('hashchange',render);render();
})();