(function(){
const posts=[
{title:'How do I prepare for the Data Structures quiz?',course:'Data Structures',author:'Ayesha Khan',time:'2 hours ago',replies:8,body:'I am revising trees and graphs. Does anyone have a good practice resource or tips for the quiz?'},
{title:'Best resources for responsive web design',course:'Web Development',author:'Hamza Ali',time:'5 hours ago',replies:12,body:'Share your favorite CSS resources, examples, or useful techniques for making layouts mobile friendly.'},
{title:'Presentation topic discussion',course:'Business Communication',author:'Sara Ahmed',time:'Yesterday',replies:5,body:'Which topic are you choosing for the final presentation? Let us coordinate and avoid duplicate topics.'},
{title:'Digital marketing project teams',course:'Digital Marketing',author:'Usman Tariq',time:'2 days ago',replies:16,body:'Looking for two classmates to join a project team. Please reply if interested.'}
];
function page(){document.querySelector('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">◆</span>UniConnect</div><nav class="nav"><a href="#"><span class="nav-icon">⌂</span>Home</a><a href="#courses"><span class="nav-icon">▤</span>My Courses</a><a href="#notes"><span class="nav-icon">▧</span>Slides & Notes</a><a class="active" href="#discussions"><span class="nav-icon">☷</span>Discussions</a><a href="#assignments"><span class="nav-icon">✓</span>Assignments</a></nav></aside><main class="main"><header class="header"><button class="menu-button">☰</button><input class="search" placeholder="Search discussions..."/><div class="user"><div class="avatar">D</div><strong>Danish</strong></div></header><section class="content"><div class="page-heading"><div><p class="eyebrow">COMMUNITY</p><h1>Discussions</h1><p class="muted">Ask questions, share ideas, and learn together.</p></div><button class="primary-btn" id="new-discussion">+ New Discussion</button></div><div class="discussion-toolbar"><input id="discussion-search" class="resource-search" placeholder="Search discussions..."/><select id="discussion-course"><option value="all">All Courses</option>${['Data Structures','Web Development','Business Communication','Digital Marketing'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="discussion-layout"><aside class="discussion-side panel"><h3>Discussion Boards</h3><button class="resource-side-active">All Discussions <span>${posts.length}</span></button><button>My Discussions <span>2</span></button><button>Unanswered <span>3</span></button><h4>Popular Topics</h4><p>#exam-preparation</p><p>#assignments</p><p>#resources</p></aside><section><div id="discussion-list" class="discussion-list">${posts.map(post).join('')}</div></section></div></section></main></div>`;bind()}
function post(p){return `<article class="discussion-card" data-course="${p.course}" data-search="${p.title} ${p.body} ${p.course}"><div class="discussion-avatar">${p.author[0]}</div><div class="discussion-body"><div class="discussion-meta"><span>${p.author} · ${p.time}</span><span class="discussion-course">${p.course}</span></div><h3>${p.title}</h3><p>${p.body}</p><div class="discussion-actions"><button>♡ ${p.replies} replies</button><button>↗ Share</button><button>☆ Save</button></div></div></article>`}
function bind(){document.querySelector('#discussion-search').oninput=filter;document.querySelector('#discussion-course').onchange=filter;document.querySelector('#new-discussion').onclick=()=>alert('New discussion form will be connected to Firebase next.');document.querySelector('.menu-button').onclick=()=>document.querySelector('.sidebar').classList.toggle('open')}
function filter(){const q=document.querySelector('#discussion-search').value.toLowerCase(),c=document.querySelector('#discussion-course').value;document.querySelectorAll('.discussion-card').forEach(x=>x.hidden=!(x.dataset.search.toLowerCase().includes(q)&&(c==='all'||x.dataset.course===c)))}
function route(){if(location.hash==='#discussions')page()}
window.addEventListener('hashchange',route);if(location.hash==='#discussions')page();
})();