const courses=[
{name:'Data Structures',code:'CS-201',teacher:'Prof. Dr. Ahmed Khan',progress:75,lessons:'18 lessons',icon:'</>',tone:'blue'},
{name:'Web Development',code:'CS-310',teacher:'Ms. Sara Malik',progress:60,lessons:'22 lessons',icon:'▣',tone:'green'},
{name:'Business Communication',code:'BA-105',teacher:'Dr. Nadia Rehman',progress:90,lessons:'14 lessons',icon:'👥',tone:'orange'},
{name:'Digital Marketing',code:'MKT-220',teacher:'Mr. Hamza Ali',progress:40,lessons:'16 lessons',icon:'▥',tone:'purple'},
{name:'Artificial Intelligence',code:'CS-450',teacher:'Dr. Usman Tariq',progress:20,lessons:'20 lessons',icon:'✦',tone:'pink'}
];
const materials=[['Lecture 01 — Introduction','Data Structures · 5 Sep 2025','PDF'],['Week 1 — Notes','Business Communication · 3 Sep 2025','DOC'],['HTML & CSS Basics','Web Development · 1 Sep 2025','PDF'],['Recorded Lecture — Week 2','Digital Marketing · 28 Aug 2025','▶']];
const notes=[
{name:'Lecture 01 — Introduction',course:'Data Structures',date:'5 Sep 2025',type:'PDF',size:'2.4 MB',icon:'▣',tone:'red'},
{name:'Week 1 — Notes',course:'Business Communication',date:'3 Sep 2025',type:'DOC',size:'1.1 MB',icon:'▤',tone:'blue'},
{name:'HTML & CSS Basics',course:'Web Development',date:'1 Sep 2025',type:'PDF',size:'3.8 MB',icon:'▣',tone:'red'},
{name:'Recorded Lecture — Week 2',course:'Digital Marketing',date:'28 Aug 2025',type:'VIDEO',size:'45 min',icon:'▶',tone:'purple'},
{name:'AI — Key Concepts',course:'Artificial Intelligence',date:'25 Aug 2025',type:'PDF',size:'2.1 MB',icon:'✦',tone:'green'},
{name:'Marketing Strategies',course:'Digital Marketing',date:'20 Aug 2025',type:'DOC',size:'900 KB',icon:'▤',tone:'blue'}
];
const assignments=[['Quiz 01','Data Structures','12 Sep 2025','Pending'],['Project Report','Web Development','15 Sep 2025','In Progress'],['Essay Submission','Business Communication','20 Sep 2025','Pending'],['Final Presentation','Digital Marketing','25 Sep 2025','Not Started']];
const classes=[['Data Structures','10:00 AM – 11:00 AM','Room A-101'],['Business Communication','12:00 PM – 1:00 PM','Room B-203'],['Web Development','2:00 PM – 3:00 PM','Online']];
const notifications=[['New note uploaded','Data Structures · 2 hours ago'],['3 new replies','Web Development discussion · 5 hours ago'],['Assignment deadline updated','Digital Marketing · 1 day ago']];
function shell(content,active='Home'){const nav=[['⌂','Home',''],['▤','My Courses','courses'],['▧','Slides & Notes','notes'],['☷','Discussions','discussions'],['✓','Assignments','assignments'],['□','Timetable','timetable'],['♧','Notifications','notifications'],['○','Profile','profile']];return `<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">◆</span>UniConnect</div><nav class="nav">${nav.map(x=>`<a class="${active===x[1]?'active':''}" href="#${x[2]||''}"><span class="nav-icon">${x[0]}</span>${x[1]}</a>`).join('')}</nav><div class="sidebar-bottom"><a href="#settings">⚙ Settings</a><a href="#help">? Help & Support</a><a href="#logout">↪ Logout</a></div></aside><main class="main"><header class="header"><button class="menu-button" aria-label="Open menu">☰</button><input class="search" placeholder="Search courses, notes, discussions..." aria-label="Search"/><div class="user"><button class="notification">♧<span class="badge">3</span></button><div class="avatar">D</div><div><strong>Danish</strong><br><span style="color:var(--muted)">Student</span></div><span>⌄</span></div></header>${content}<nav class="mobile-nav"><a class="${active==='Home'?'active':''}" href="#"><span class="nav-icon">⌂</span>Home</a><a class="${active==='My Courses'?'active':''}" href="#courses"><span class="nav-icon">▤</span>Courses</a><a class="${active==='Slides & Notes'?'active':''}" href="#notes"><span class="nav-icon">▧</span>Notes</a><a href="#discussions"><span class="nav-icon">☷</span>Discussions</a><a href="#profile"><span class="nav-icon">○</span>Profile</a></nav></main></div>`}
function courseCard(c){return `<article class="course-card course-${c.tone}"><div class="course-icon">${c.icon}</div><h3>${c.name}</h3><p>${c.code}</p><p>${c.teacher}</p><div class="progress"><span style="width:${c.progress}%"></span></div><p>${c.progress}% complete</p></article>`}
function row(title,meta,icon='▤',extra=''){return `<div class="row"><div class="file-icon">${icon}</div><div class="row-main"><strong>${title}</strong><span>${meta}</span></div>${extra}</div>`}
function dashboard(){return shell(`<section class="content"><div class="welcome"><h1>Welcome back, Danish! 👋</h1><p>Keep learning, keep growing.</p></div><div class="section-title"><h2>My Courses</h2><a class="link" href="#courses">View All</a></div><div class="grid course-grid">${courses.slice(0,4).map(courseCard).join('')}</div><div class="grid two-col"><section><div class="section-title"><h2>Recent Slides & Notes</h2><a class="link" href="#notes">View All</a></div><div class="panel list">${materials.map(m=>row(m[0],m[1],m[2],'↓')).join('')}</div></section><section><div class="section-title"><h2>Upcoming Assignments</h2><a class="link" href="#assignments">View All</a></div><div class="panel list">${assignments.map(a=>row(a[0],`${a[1]} · Due ${a[2]}`,'▤',`<span class="status ${a[3]==='Pending'?'pending':a[3]==='In Progress'?'progress':''}">${a[3]}</span>`)).join('')}</div></section></div></section>`,'Home')}
function coursesPage(){return shell(`<section class="content"><div class="page-heading"><div><p class="eyebrow">LEARNING CENTER</p><h1>My Courses</h1><p class="muted">Manage your enrolled courses and continue learning.</p></div><button class="primary-btn">+ Explore Courses</button></div><div class="tabs"><button class="selected">All Courses</button><button>Current</button><button>Upcoming</button><button>Completed</button></div><div class="grid course-grid courses-page-grid">${courses.map(c=>`<article class="course-card course-${c.tone}"><div class="course-top"><div class="course-icon">${c.icon}</div><button class="more">⋮</button></div><h3>${c.name}</h3><p>${c.code} · ${c.teacher}</p><div class="course-meta"><span>${c.lessons}</span><strong>${c.progress}%</strong></div><div class="progress"><span style="width:${c.progress}%"></span></div><a class="course-open" href="#course-details">Open Course <span>→</span></a></article>`).join('')}</div></section>`,'My Courses')}
function detailsPage(){const c=courses[0];return shell(`<section class="content"><a class="back-link" href="#courses">← Back to My Courses</a><div class="course-hero"><div class="course-icon">${c.icon}</div><div><p class="eyebrow">${c.code}</p><h1>${c.name}</h1><p>${c.teacher} · ${c.lessons}</p></div><div class="hero-progress"><strong>${c.progress}%</strong><span>Course progress</span><div class="progress"><span style="width:${c.progress}%"></span></div></div></div><div class="tabs detail-tabs"><button>Overview</button><button class="selected">Content</button><button>Assignments</button><button>Quizzes</button><button>Discussions</button></div><div class="grid two-col"><section><div class="section-title"><h2>Course Content</h2><span class="muted">18 lessons</span></div><div class="panel list">${materials.map((m,i)=>row(`Unit ${i+1} — ${m[0]}`,`${m[1]} · ${i<2?'Completed':'Not started'}`,m[2],'<button class="icon-btn">↓</button>')).join('')}</div></section><section><div class="section-title"><h2>About this course</h2></div><div class="panel"><p class="muted">Build strong foundations in data structures, algorithms, and problem solving through guided lectures and practical exercises.</p><div class="detail-stat"><strong>12</strong><span>Completed lessons</span></div><div class="detail-stat"><strong>6</strong><span>Pending lessons</span></div></div></section></div></section>`,'My Courses')}
function notesPage(){return shell(`<section class="content"><div class="page-heading"><div><p class="eyebrow">RESOURCE LIBRARY</p><h1>Slides & Notes</h1><p class="muted">Find lecture slides, study notes, recordings, and useful resources.</p></div><button class="primary-btn" id="upload-note">+ Upload Note</button></div><div class="resource-toolbar"><input id="note-search" class="resource-search" placeholder="Search notes and resources..."/><select id="course-filter"><option value="all">All Courses</option>${courses.map(c=>`<option>${c.name}</option>`).join('')}</select><select id="type-filter"><option value="all">All Types</option><option>PDF</option><option>DOC</option><option>VIDEO</option></select></div><div class="resource-layout"><aside class="resource-side panel"><h3>Browse Resources</h3><button class="resource-side-active">All Resources <span>${notes.length}</span></button><button>My Favorites <span>2</span></button><button>Recently Viewed <span>4</span></button><h4>File Types</h4><p>▣ PDF Documents</p><p>▤ Word Notes</p><p>▶ Recorded Lectures</p></aside><section><div class="resource-header"><h2>All Resources</h2><span class="muted">${notes.length} files available</span></div><div id="notes-grid" class="notes-grid">${notes.map(noteCard).join('')}</div></section></div></section>`,'Slides & Notes')}
function noteCard(n){return `<article class="note-card" data-course="${n.course}" data-type="${n.type}" data-search="${n.name} ${n.course}"><div class="note-card-top"><div class="file-icon file-${n.tone}">${n.icon}</div><button class="favorite">☆</button></div><span class="note-type">${n.type}</span><h3>${n.name}</h3><p>${n.course}</p><div class="note-footer"><span>${n.date} · ${n.size}</span><button class="download-btn">↓</button></div></article>`}
function render(){const hash=location.hash.replace('#','');document.querySelector('#app').innerHTML=hash==='courses'?coursesPage():hash==='course-details'?detailsPage():hash==='notes'?notesPage():dashboard();bind()}
function bind(){document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>setTimeout(render,0)));document.querySelector('.menu-button')?.addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));document.querySelector('.search')?.addEventListener('input',e=>{const t=e.target.value.toLowerCase();document.querySelectorAll('.course-card,.row,.note-card').forEach(x=>x.hidden=t&&!x.textContent.toLowerCase().includes(t))});const filter=()=>{const q=(document.querySelector('#note-search')?.value||'').toLowerCase(),c=document.querySelector('#course-filter')?.value||'all',t=document.querySelector('#type-filter')?.value||'all';document.querySelectorAll('.note-card').forEach(x=>x.hidden=!(x.dataset.search.toLowerCase().includes(q)&&(c==='all'||x.dataset.course===c)&&(t==='all'||x.dataset.type===t)))};document.querySelector('#note-search')?.addEventListener('input',filter);document.querySelector('#course-filter')?.addEventListener('change',filter);document.querySelector('#type-filter')?.addEventListener('change',filter);document.querySelectorAll('.favorite').forEach(b=>b.addEventListener('click',()=>b.textContent=b.textContent==='☆'?'★':'☆'));document.querySelectorAll('.download-btn').forEach(b=>b.addEventListener('click',()=>{b.textContent='✓';setTimeout(()=>b.textContent='↓',1000)}))}
window.addEventListener('hashchange',render);render();
