const courses = [
  { name: 'Data Structures', code: 'CS-201', teacher: 'Prof. Dr. Ahmed Khan', progress: 75 },
  { name: 'Web Development', code: 'CS-310', teacher: 'Ms. Sara Malik', progress: 60 },
  { name: 'Business Communication', code: 'BA-105', teacher: 'Dr. Nadia Rehman', progress: 90 },
  { name: 'Digital Marketing', code: 'MKT-220', teacher: 'Mr. Hamza Ali', progress: 40 }
];
const materials = [['Lecture 01 — Introduction','Data Structures · 5 Sep 2025','PDF'],['Week 1 — Notes','Business Communication · 3 Sep 2025','DOC'],['HTML & CSS Basics','Web Development · 1 Sep 2025','PDF'],['Recorded Lecture — Week 2','Digital Marketing · 28 Aug 2025','▶']];
const assignments = [['Quiz 01','Data Structures','12 Sep 2025','Pending'],['Project Report','Web Development','15 Sep 2025','In Progress'],['Essay Submission','Business Communication','20 Sep 2025','Pending'],['Final Presentation','Digital Marketing','25 Sep 2025','Not Started']];
const classes = [['Data Structures','10:00 AM – 11:00 AM','Room A-101'],['Business Communication','12:00 PM – 1:00 PM','Room B-203'],['Web Development','2:00 PM – 3:00 PM','Online']];
const notifications = [['New note uploaded','Data Structures · 2 hours ago'],['3 new replies','Web Development discussion · 5 hours ago'],['Assignment deadline updated','Digital Marketing · 1 day ago']];
function courseCard(c,i){return `<article class="course-card"><div class="course-icon">${['</>','▣','👥','▥'][i]}</div><h3>${c.name}</h3><p>${c.code}</p><p>${c.teacher}</p><div class="progress"><span style="width:${c.progress}%"></span></div><p>${c.progress}% complete</p></article>`}
function listRow(title,meta,icon='▤',extra=''){return `<div class="row"><div class="file-icon">${icon}</div><div class="row-main"><strong>${title}</strong><span>${meta}</span></div>${extra}</div>`}
function assignmentRow(a){const type=a[3]==='Pending'?'pending':a[3]==='In Progress'?'progress':'';return listRow(a[0],`${a[1]} · Due ${a[2]}`,'▤',`<span class="status ${type}">${a[3]}</span>`)}
function dashboard(){document.querySelector('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">◆</span>UniConnect</div><nav class="nav">${[['⌂','Home'],['▤','My Courses'],['▧','Slides & Notes'],['☷','Discussions'],['✓','Assignments'],['□','Timetable'],['♧','Notifications'],['○','Profile']].map((x,i)=>`<a class="${i===0?'active':''}" href="#${x[1].toLowerCase().replaceAll(' ','-')}"><span class="nav-icon">${x[0]}</span>${x[1]}</a>`).join('')}</nav><div class="sidebar-bottom"><a href="#settings">⚙ Settings</a><a href="#help">? Help & Support</a><a href="#logout">↪ Logout</a></div></aside><main class="main"><header class="header"><button class="menu-button" aria-label="Open menu">☰</button><input class="search" placeholder="Search courses, notes, discussions..." aria-label="Search"/><div class="user"><button class="notification" aria-label="Notifications">♧<span class="badge">3</span></button><div class="avatar">D</div><div><strong>Danish</strong><br><span style="color:var(--muted)">Student</span></div><span>⌄</span></div></header><section class="content"><div class="welcome"><h1>Welcome back, Danish! 👋</h1><p>Keep learning, keep growing.</p></div><div class="section-title"><h2>My Courses</h2><a class="link" href="#courses">View All</a></div><div class="grid course-grid">${courses.map(courseCard).join('')}</div><div class="grid two-col"><section><div class="section-title"><h2>Recent Slides & Notes</h2><a class="link" href="#notes">View All</a></div><div class="panel list">${materials.map(m=>listRow(m[0],m[1],m[2],'↓')).join('')}</div></section><section><div class="section-title"><h2>Upcoming Assignments</h2><a class="link" href="#assignments">View All</a></div><div class="panel list">${assignments.map(assignmentRow).join('')}</div></section></div><div class="grid three-col"><section><div class="section-title"><h2>Today’s Classes</h2><a class="link" href="#timetable">View All</a></div><div class="panel list">${classes.map(x=>listRow(x[0],`${x[1]} · ${x[2]}`,'•')).join('')}</div></section><section><div class="section-title"><h2>Notifications</h2><a class="link" href="#notifications">View All</a></div><div class="panel list">${notifications.map(x=>listRow(x[0],x[1],'•')).join('')}</div></section><section><div class="section-title"><h2>Your Progress</h2></div><div class="panel"><h3>Small progress leads to big results.</h3><p style="color:var(--muted)">Overall learning progress</p><div class="progress"><span style="width:68%"></span></div><p><strong>68%</strong> complete</p></div></section></div></section><nav class="mobile-nav"><a class="active" href="#"><span class="nav-icon">⌂</span>Home</a><a href="#courses"><span class="nav-icon">▤</span>Courses</a><a href="#notes"><span class="nav-icon">▧</span>Notes</a><a href="#discussions"><span class="nav-icon">☷</span>Discussions</a><a href="#profile"><span class="nav-icon">○</span>Profile</a></nav></main></div>`;bindInteractions()}
function bindInteractions(){document.querySelectorAll('.nav a,.mobile-nav a').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();document.querySelectorAll('.nav a,.mobile-nav a').forEach(item=>item.classList.remove('active'));document.querySelectorAll(`[href="${link.getAttribute('href')}"]`).forEach(item=>item.classList.add('active'));}));const menu=document.querySelector('.menu-button');menu.addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));document.querySelector('.search').addEventListener('input',e=>{const term=e.target.value.toLowerCase();document.querySelectorAll('.course-card,.row').forEach(item=>item.hidden=term&&!item.textContent.toLowerCase().includes(term))})}
dashboard();
