const courses=[
{name:'Data Structures',code:'CS-201',teacher:'Prof. Dr. Ahmed Khan',progress:75,lessons:'18 lessons',icon:'</>',tone:'blue'},
{name:'Web Development',code:'CS-310',teacher:'Ms. Sara Malik',progress:60,lessons:'22 lessons',icon:'▣',tone:'green'},
{name:'Business Communication',code:'BA-105',teacher:'Dr. Nadia Rehman',progress:90,lessons:'14 lessons',icon:'👥',tone:'orange'},
{name:'Digital Marketing',code:'MKT-220',teacher:'Mr. Hamza Ali',progress:40,lessons:'16 lessons',icon:'▥',tone:'purple'},
{name:'Artificial Intelligence',code:'CS-450',teacher:'Dr. Usman Tariq',progress:20,lessons:'20 lessons',icon:'✦',tone:'pink'}
];
const materials=[['Lecture 01 — Introduction','Data Structures · 5 Sep 2025','PDF'],['Week 1 — Notes','Business Communication · 3 Sep 2025','DOC'],['HTML & CSS Basics','Web Development · 1 Sep 2025','PDF'],['Recorded Lecture — Week 2','Digital Marketing · 28 Aug 2025','▶']];
const assignments=[['Quiz 01','Data Structures','12 Sep 2025','Pending'],['Project Report','Web Development','15 Sep 2025','In Progress'],['Essay Submission','Business Communication','20 Sep 2025','Pending'],['Final Presentation','Digital Marketing','25 Sep 2025','Not Started']];
const classes=[['Data Structures','10:00 AM – 11:00 AM','Room A-101'],['Business Communication','12:00 PM – 1:00 PM','Room B-203'],['Web Development','2:00 PM – 3:00 PM','Online']];
const notifications=[['New note uploaded','Data Structures · 2 hours ago'],['3 new replies','Web Development discussion · 5 hours ago'],['Assignment deadline updated','Digital Marketing · 1 day ago']];
const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function shell(content,active='Home'){const nav=[['⌂','Home',''],['▤','My Courses','courses'],['▧','Slides & Notes','notes'],['☷','Discussions','discussions'],['✓','Assignments','assignments'],['□','Timetable','timetable'],['♧','Notifications','notifications'],['○','Profile','profile']];return `<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">◆</span>UniConnect</div><nav class="nav">${nav.map(x=>`<a class="${active===x[1]?'active':''}" href="#${x[2]||''}"><span class="nav-icon">${x[0]}</span>${x[1]}</a>`).join('')}</nav><div class="sidebar-bottom"><a href="#settings">⚙ Settings</a><a href="#help">? Help & Support</a><a href="#logout">↪ Logout</a></div></aside><main class="main"><header class="header"><button class="menu-button" aria-label="Open menu">☰</button><input class="search" placeholder="Search courses, notes, discussions..." aria-label="Search"/><div class="user"><button class="notification">♧<span class="badge">3</span></button><div class="avatar">D</div><div><strong>Danish</strong><br><span style="color:var(--muted)">Student</span></div><span>⌄</span></div></header>${content}<nav class="mobile-nav"><a class="${active==='Home'?'active':''}" href="#"><span class="nav-icon">⌂</span>Home</a><a class="${active==='My Courses'?'active':''}" href="#courses"><span class="nav-icon">▤</span>Courses</a><a href="#notes"><span class="nav-icon">▧</span>Notes</a><a href="#discussions"><span class="nav-icon">☷</span>Discussions</a><a href="#profile"><span class="nav-icon">○</span>Profile</a></nav></main></div>`}
function courseCard(c){return `<article class="course-card course-${c.tone}"><div class="course-icon">${c.icon}</div><h3>${c.name}</h3><p>${c.code}</p><p>${c.teacher}</p><div class="progress"><span style="width:${c.progress}%"></span></div><p>${c.progress}% complete</p></article>`}
function row(title,meta,icon='▤',extra=''){return `<div class="row"><div class="file-icon">${icon}</div><div class="row-main"><strong>${title}</strong><span>${meta}</span></div>${extra}</div>`}
function dashboard(){return shell(`<section class="content"><div class="welcome"><h1>Welcome back, Danish! 👋</h1><p>Keep learning, keep growing.</p></div><div class="section-title"><h2>My Courses</h2><a class="link" href="#courses">View All</a></div><div class="grid course-grid">${courses.slice(0,4).map(courseCard).join('')}</div><div class="grid two-col"><section><div class="section-title"><h2>Recent Slides & Notes</h2><a class="link" href="#notes">View All</a></div><div class="panel list">${materials.map(m=>row(m[0],m[1],m[2],'↓')).join('')}</div></section><section><div class="section-title"><h2>Upcoming Assignments</h2><a class="link" href="#assignments">View All</a></div><div class="panel list">${assignments.map(a=>row(a[0],`${a[1]} · Due ${a[2]}`,'▤',`<span class="status ${a[3]==='Pending'?'pending':a[3]==='In Progress'?'progress':''}">${a[3]}</span>`)).join('')}</div></section></div><div class="grid three-col"><section><div class="section-title"><h2>Today’s Classes</h2></div><div class="panel list">${classes.map(x=>row(x[0],`${x[1]} · ${x[2]}`,'•')).join('')}</div></section><section><div class="section-title"><h2>Notifications</h2></div><div class="panel list">${notifications.map(x=>row(x[0],x[1],'•')).join('')}</div></section><section><div class="section-title"><h2>Your Progress</h2></div><div class="panel"><h3>Small progress leads to big results.</h3><p style="color:var(--muted)">Overall learning progress</p><div class="progress"><span style="width:68%"></span></div><p><strong>68%</strong> complete</p></div></section></div></section>`,'Home')}
function coursesPage(){return shell(`<section class="content"><div class="page-heading"><div><p class="eyebrow">LEARNING CENTER</p><h1>My Courses</h1><p class="muted">Manage your enrolled courses and continue learning.</p></div><button class="primary-btn">+ Explore Courses</button></div><div class="tabs"><button class="selected">All Courses</button><button>Current</button><button>Upcoming</button><button>Completed</button></div><div class="grid course-grid courses-page-grid">${courses.map(c=>`<article class="course-card course-${c.tone}"><div class="course-top"><div class="course-icon">${c.icon}</div><button class="more">⋮</button></div><h3>${c.name}</h3><p>${c.code} · ${c.teacher}</p><div class="course-meta"><span>${c.lessons}</span><strong>${c.progress}%</strong></div><div class="progress"><span style="width:${c.progress}%"></span></div><a class="course-open" href="#course-details">Open Course <span>→</span></a></article>`).join('')}</div></section>`,'My Courses')}
function detailsPage(){const c=courses[0];return shell(`<section class="content"><a class="back-link" href="#courses">← Back to My Courses</a><div class="course-hero"><div class="course-icon">${c.icon}</div><div><p class="eyebrow">${c.code}</p><h1>${c.name}</h1><p>${c.teacher} · ${c.lessons}</p></div><div class="hero-progress"><strong>${c.progress}%</strong><span>Course progress</span><div class="progress"><span style="width:${c.progress}%"></span></div></div></div><div class="tabs detail-tabs"><button>Overview</button><button class="selected">Content</button><button>Assignments</button><button>Quizzes</button><button>Discussions</button></div><div class="grid two-col"><section><div class="section-title"><h2>Course Content</h2><span class="muted">18 lessons</span></div><div class="panel list">${materials.map((m,i)=>row(`Unit ${i+1} — ${m[0]}`,`${m[1]} · ${i<2?'Completed':'Not started'}`,m[2],'<button class="icon-btn">↓</button>')).join('')}</div></section><section><div class="section-title"><h2>About this course</h2></div><div class="panel"><p class="muted">Build strong foundations in data structures, algorithms, and problem solving through guided lectures and practical exercises.</p><div class="detail-stat"><strong>12</strong><span>Completed lessons</span></div><div class="detail-stat"><strong>6</strong><span>Pending lessons</span></div></div></section></div></section>`,'My Courses')}
function render(){const hash=location.hash.replace('#','');document.querySelector('#app').innerHTML=hash==='courses'?coursesPage():hash==='course-details'?detailsPage():dashboard();bind()}
function bind(){document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>setTimeout(render,0)));document.querySelector('.menu-button')?.addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));document.querySelector('.search')?.addEventListener('input',e=>{const t=e.target.value.toLowerCase();document.querySelectorAll('.course-card,.row').forEach(x=>x.hidden=t&&!x.textContent.toLowerCase().includes(t))})}
window.addEventListener('hashchange',render);render();
