(function(){
  const notes=[
    {title:'Lecture 01 — Introduction',course:'Data Structures',date:'5 Sep 2025',type:'PDF',size:'2.4 MB',tone:'red'},
    {title:'Week 1 — Communication Basics',course:'Business Communication',date:'3 Sep 2025',type:'DOC',size:'1.1 MB',tone:'blue'},
    {title:'HTML & CSS Basics',course:'Web Development',date:'1 Sep 2025',type:'PDF',size:'3.2 MB',tone:'purple'},
    {title:'Recorded Lecture — Week 2',course:'Digital Marketing',date:'28 Aug 2025',type:'VIDEO',size:'45 min',tone:'pink'},
    {title:'AI — Key Concepts',course:'Artificial Intelligence',date:'25 Aug 2025',type:'PDF',size:'2.8 MB',tone:'green'},
    {title:'Marketing Strategies',course:'Digital Marketing',date:'22 Aug 2025',type:'DOC',size:'980 KB',tone:'orange'}
  ];
  function renderNotes(){
    if(location.hash!=='#notes') return;
    const app=document.querySelector('#app'); if(!app) return;
    app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">◆</span>UniConnect</div><nav class="nav"><a href="#"><span class="nav-icon">⌂</span>Home</a><a href="#courses"><span class="nav-icon">▤</span>My Courses</a><a class="active" href="#notes"><span class="nav-icon">▧</span>Slides & Notes</a><a href="#discussions"><span class="nav-icon">☷</span>Discussions</a><a href="#assignments"><span class="nav-icon">✓</span>Assignments</a><a href="#timetable"><span class="nav-icon">□</span>Timetable</a><a href="#notifications"><span class="nav-icon">♧</span>Notifications</a><a href="#profile"><span class="nav-icon">○</span>Profile</a></nav><div class="sidebar-bottom"><a href="#settings">⚙ Settings</a><a href="#help">? Help & Support</a><a href="#logout">↪ Logout</a></div></aside><main class="main"><header class="header"><button class="menu-button" aria-label="Open menu">☰</button><input class="search notes-search" placeholder="Search notes, lectures, resources..." aria-label="Search notes"/><div class="user"><button class="notification">♧<span class="badge">3</span></button><div class="avatar">D</div><div><strong>Danish</strong><br><span style="color:var(--muted)">Student</span></div><span>⌄</span></div></header><section class="content"><div class="page-heading"><div><p class="eyebrow">LEARNING LIBRARY</p><h1>Slides & Notes</h1><p class="muted">Find your lecture slides, notes, recordings, and study resources.</p></div><button class="primary-btn">+ Upload Resource</button></div><div class="notes-toolbar"><div class="tabs"><button class="selected" data-filter="All">All Resources</button><button data-filter="PDF">PDFs</button><button data-filter="DOC">Documents</button><button data-filter="VIDEO">Videos</button></div><select class="course-filter"><option>All Courses</option><option>Data Structures</option><option>Web Development</option><option>Business Communication</option><option>Digital Marketing</option><option>Artificial Intelligence</option></select></div><div class="notes-grid">${notes.map(n=>`<article class="note-card" data-type="${n.type}" data-course="${n.course}"><div class="note-card-top"><div class="file-icon note-${n.tone}">${n.type==='VIDEO'?'▶':n.type}</div><button class="more">⋮</button></div><h3>${n.title}</h3><p>${n.course}</p><div class="note-footer"><span>${n.date} · ${n.size}</span><button class="download-btn" aria-label="Download ${n.title}">↓</button></div></article>`).join('')}</div></section><nav class="mobile-nav"><a href="#"><span class="nav-icon">⌂</span>Home</a><a href="#courses"><span class="nav-icon">▤</span>Courses</a><a class="active" href="#notes"><span class="nav-icon">▧</span>Notes</a><a href="#discussions"><span class="nav-icon">☷</span>Discussions</a><a href="#profile"><span class="nav-icon">○</span>Profile</a></nav></main></div>`;
    app.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>setTimeout(renderNotes,0)));
    app.querySelector('.menu-button')?.addEventListener('click',()=>app.querySelector('.sidebar').classList.toggle('open'));
    const filter=()=>{const term=(app.querySelector('.notes-search')?.value||'').toLowerCase(), course=app.querySelector('.course-filter')?.value||'All Courses', active=app.querySelector('.tabs .selected')?.dataset.filter||'All';app.querySelectorAll('.note-card').forEach(card=>{card.hidden=!!((term&&!card.textContent.toLowerCase().includes(term))||(course!=='All Courses'&&card.dataset.course!==course)||(active!=='All'&&card.dataset.type!==active))})};
    app.querySelector('.notes-search')?.addEventListener('input',filter); app.querySelector('.course-filter')?.addEventListener('change',filter); app.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>{app.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');filter()}));
  }
  window.addEventListener('hashchange',renderNotes); renderNotes();
})();
