(function(){
'use strict';
const navItems=[
  ['⌂','Home','#student-dashboard'],['▤','My Courses','#courses'],['▧','Slides & Notes','#notes'],['☷','Discussions','#discussions'],['✓','Assignments','#assignments'],['□','Timetable','#timetable'],['♧','Notifications','#notifications'],['○','Profile','#profile']
];
function sidebar(active){return `<aside class="student-sidebar"><div class="student-brand"><span class="brand-mark">◆</span><strong>UniConnect</strong></div><nav>${navItems.map(x=>`<a class="${active===x[1]?'active':''}" href="${x[2]}"><span>${x[0]}</span>${x[1]}</a>`).join('')}</nav><div class="student-sidebar-bottom"><a href="#settings">⚙ Settings</a><a href="#help">? Help & Support</a><a href="#logout">↪ Logout</a></div></aside>`}
function top(active,placeholder){return `<header class="student-topbar"><button class="student-menu-button" aria-label="Open navigation">☰</button><div class="student-mobile-brand"><span class="brand-mark">◆</span><strong>UniConnect</strong></div><div class="student-search"><span>⌕</span><input aria-label="Search" placeholder="${placeholder}" /></div><div class="student-top-actions"><button class="icon-action" aria-label="Notifications">♧<b>3</b></button><div class="student-user"><span class="user-avatar">D</span><span><strong>Danish</strong><small>Student</small></span><span class="user-chevron">⌄</span></div></div></header>`}
function page(active,content,placeholder){document.querySelector('#app').innerHTML=`<div class="student-layout">${sidebar(active)}<main class="student-main">${top(active,placeholder)}<section class="student-content">${content}</section></main></div>`;bindMenu()}
function courses(){page('My Courses',`<div class="student-page-heading"><div><p class="student-eyebrow-dark">LEARNING CENTER</p><h1>My Courses</h1><p>View your enrolled courses and continue learning.</p></div></div><div class="student-course-grid">${[
['Data Structures','CS-201','Prof. Dr. Ahmed Khan','75%','blue'],['Web Development','CS-310','Ms. Sara Malik','60%','green'],['Business Communication','BA-105','Dr. Nadia Rehman','90%','orange'],['Digital Marketing','MKT-220','Mr. Hamza Ali','40%','purple'],['Artificial Intelligence','CS-450','Dr. Usman Tariq','20%','pink']
].map(c=>`<article class="student-course-card"><div class="student-course-icon ${c[4]}\">▣</div><h3>${c[0]}</h3><p>${c[1]} · ${c[2]}</p><div class="student-course-progress"><span style="width:${c[3]}"></span></div><div class="student-course-footer"><small>${c[3]} complete</small><a href="#course-details">Open course →</a></div></article>`).join('')}</div>`,'Search courses...')}
function discussions(){const posts=[['How do I prepare for the Data Structures quiz?','Ayesha Khan','Data Structures','I am revising trees and graphs. Does anyone have a good practice resource or tips for the quiz?','8 replies'],['Best resources for responsive web design','Hamza Ali','Web Development','Share your favorite CSS resources, examples, or useful techniques for making layouts mobile friendly.','12 replies'],['Presentation topic discussion','Sara Ahmed','Business Communication','Which topic are you choosing for the final presentation? Let us coordinate and avoid duplicate topics.','5 replies'],['Digital marketing project teams','Usman Tariq','Digital Marketing','Looking for two classmates to join a project team. Please reply if interested.','16 replies']];page('Discussions',`<div class="student-page-heading"><div><p class="student-eyebrow-dark">CLASS COMMUNITY</p><h1>Discussions</h1><p>Ask questions, share ideas, and learn together.</p></div><button class="student-primary-button">+ New Discussion</button></div><div class="student-discussion-toolbar"><input id="student-discussion-search" placeholder="Search discussions..."/><select id="student-discussion-course"><option value="all">All Courses</option><option>Data Structures</option><option>Web Development</option><option>Business Communication</option><option>Digital Marketing</option></select></div><div class="student-discussion-list">${posts.map(p=>`<article class="student-discussion-card" data-course="${p[2]}" data-search="${p.join(' ').toLowerCase()}"><div class="student-discussion-avatar">${p[1][0]}</div><div><div class="student-discussion-meta"><span>${p[1]} · 2 hours ago</span><b>${p[2]}</b></div><h3>${p[0]}</h3><p>${p[3]}</p><div class="student-discussion-actions">♡ ${p[4]} <span>↗ Share</span><span>☆ Save</span></div></div></article>`).join('')}</div>`,'Search discussions...');const f=()=>{const q=document.querySelector('#student-discussion-search').value.toLowerCase(),c=document.querySelector('#student-discussion-course').value;document.querySelectorAll('.student-discussion-card').forEach(x=>x.hidden=!(x.dataset.search.includes(q)&&(c==='all'||x.dataset.course===c)))};document.querySelector('#student-discussion-search').oninput=f;document.querySelector('#student-discussion-course').onchange=f}
function bindMenu(){document.querySelector('.student-menu-button')?.addEventListener('click',()=>document.querySelector('.student-sidebar')?.classList.toggle('open'))}
function enhanceDashboard(){const root=document.querySelector('.student-page');if(!root||document.querySelector('.student-sidebar'))return;const old=root.innerHTML;root.className='student-layout';root.innerHTML=`${sidebar('Home')}<main class="student-main">${old}</main>`;bindMenu()}
function route(){if(location.hash==='#courses')courses();else if(location.hash==='#discussions')discussions();else if(location.hash==='#student-dashboard'||location.hash===''||location.hash==='#')enhanceDashboard()}
window.addEventListener('hashchange',()=>setTimeout(route,0));setTimeout(route,0);
})();
