(function(){
'use strict';
function renderStudent(){
  if(location.hash!=='#student-dashboard') return;
  const app=document.getElementById('app'); if(!app) return;
  app.innerHTML=`<main class="student-page">
    <section class="student-hero"><div class="student-welcome"><div class="student-avatar">DR</div><div><p class="student-eyebrow">MY CLASS MATTERS <span class="live-dot"></span> STUDENT SPACE</p><h1>Welcome back, Danish</h1><p class="student-subtitle">Your learning journey, organized in one place.</p></div></div><div class="student-hero-meta"><span class="student-status"><i></i> Academic account active</span><span class="student-date">Fall Semester · 2026</span></div></section>
    <section class="student-overview"><article class="overview-card"><div class="overview-icon blue">⌂</div><div><span>Assigned class</span><strong>BSCS 4A</strong><small>Computer Science</small></div><b>↗</b></article><article class="overview-card"><div class="overview-icon green">✦</div><div><span>Assigned SVL</span><strong>Dr. Ayesha Khan</strong><small>Your class supervisor</small></div><b>↗</b></article><article class="overview-card"><div class="overview-icon purple">♧</div><div><span>Classmates</span><strong>32 Students</strong><small>Connected to your class</small></div><b>↗</b></article><article class="overview-card"><div class="overview-icon">✓</div><div><span>Attendance</span><strong>88% <em>Good</em></strong><small>Current attendance</small></div><b>↗</b></article></section>
    <section class="student-quick-actions"><a class="quick-action featured" href="#class-room"><span class="quick-symbol">◉</span><span><strong>Class Room</strong><small>Connect with your class</small></span><b>→</b></a><a class="quick-action" href="#timetable"><span class="quick-symbol">□</span><span><strong>Timetable</strong><small>View today’s schedule</small></span><b>→</b></a><a class="quick-action" href="#notes"><span class="quick-symbol">▤</span><span><strong>Slides & Notes</strong><small>Study resources</small></span><b>→</b></a><a class="quick-action" href="#assignments"><span class="quick-symbol">✓</span><span><strong>Assignments</strong><small>Track your deadlines</small></span><b>→</b></a></section>
    <section class="student-content-grid"><article class="student-panel"><div class="panel-heading"><div><p class="panel-kicker">YOUR SCHEDULE</p><h2>Today’s timetable</h2></div><a href="#timetable">View full timetable →</a></div><div class="schedule-list"><div class="schedule-row active"><time>09:00<span>AM</span></time><span class="schedule-line"></span><div class="schedule-info"><strong>Web Engineering</strong><small>Room 204 · Dr. Ayesha Khan</small></div><span class="schedule-tag">Next</span></div><div class="schedule-row"><time>11:00<span>AM</span></time><span class="schedule-line"></span><div class="schedule-info"><strong>Database Systems</strong><small>Room 108 · Mr. Hamza Ali</small></div></div><div class="schedule-row"><time>02:00<span>PM</span></time><span class="schedule-line"></span><div class="schedule-info"><strong>Software Project</strong><small>Lab 3 · Dr. Ayesha Khan</small></div></div></div></article><article class="student-panel"><div class="panel-heading"><div><p class="panel-kicker">CLASS UPDATES</p><h2>Latest notices</h2></div><a href="#notifications">See all →</a></div><div class="notice-list"><a class="notice-item" href="#notifications"><span class="notice-icon orange">!</span><span><strong>Project proposal submission</strong><small>Submit your proposal before Friday.</small><time>Today · 2 hours ago</time></span><b>›</b></a><a class="notice-item" href="#notifications"><span class="notice-icon blue">▣</span><span><strong>Next class presentation</strong><small>Presentations begin next Monday.</small><time>Yesterday</time></span><b>›</b></a></div></article><article class="student-panel"><div class="panel-heading"><div><p class="panel-kicker">STUDY MATERIAL</p><h2>SVL slides & notes</h2></div><a href="#notes">Open library →</a></div><div class="resource-list"><a class="resource-item" href="#notes"><span class="file-icon pdf">PDF</span><span><strong>Web Engineering — Lecture 06</strong><small>Uploaded today · 2.4 MB</small></span><b>↓</b></a><a class="resource-item" href="#notes"><span class="file-icon doc">DOC</span><span><strong>Software Project Guidelines</strong><small>Uploaded yesterday · 1.1 MB</small></span><b>↓</b></a></div></article><article class="student-panel"><div class="panel-heading"><div><p class="panel-kicker">YOUR COMMUNITY</p><h2>Class room</h2></div><a href="#class-room">Open room →</a></div><div class="community-preview"><div class="community-avatars"><span>AK</span><span>HA</span><span>SR</span><span>+29</span></div><strong>Stay connected with BSCS 4A</strong><p>Ask questions, share ideas, discuss assignments and connect with your classmates.</p><a class="community-link" href="#class-room">Enter class room <span>→</span></a></div></article></section><footer class="student-footer"><span>MCM Student Portal</span><span class="footer-divider"></span><a href="#help">Need help?</a><span class="footer-divider"></span><a href="#profile">View profile</a></footer>
  </main>`;
}
window.renderStudent=renderStudent;
window.addEventListener('hashchange',renderStudent);
renderStudent();
})();