(function(){
'use strict';
const bucket='mcm-notes';
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeName(v){return String(v||'file').replace(/[^a-z0-9._-]/gi,'-')}
async function assignedClasses(){const user=await window.mcmDb.user();const rows=await window.mcmDb.allMembers();const ids=rows.filter(x=>x.user_id===user?.id).map(x=>String(x.class_id));return (await window.mcmDb.classes()).filter(c=>ids.includes(String(c.id)))}
async function saveNotice(e){e.preventDefault();const f=e.target;const title=f.title.value.trim(),body=f.body.value.trim(),classId=f.classId.value;if(!title||!body||!classId)return alert('Please complete all fields.');try{await window.mcmDb.addNotice({class_id:Number(classId),title,body,created_by:(await window.mcmDb.user())?.id});alert('Notice published successfully.');f.reset();loadContent()}catch(err){alert(err.message||'Unable to publish notice.')}}
async function uploadNote(e){e.preventDefault();const f=e.target,file=f.file.files[0],title=f.noteTitle.value.trim(),classId=f.noteClass.value;if(!file||!title||!classId)return alert('Select a file, title and class.');const client=window.initMcmSupabase();const user=await window.mcmDb.user();if(!client||!user)return alert('Please login first.');try{const path=`${classId}/${user.id}/${Date.now()}-${safeName(file.name)}`;const up=await client.storage.from(bucket).upload(path,file,{upsert:false});if(up.error)throw up.error;const url=client.storage.from(bucket).getPublicUrl(path).data.publicUrl;await window.mcmDb.addNote({class_id:Number(classId),title,file_url:url,uploaded_by:user.id});alert('Slides / notes uploaded successfully.');f.reset();loadContent()}catch(err){alert(err.message||'Unable to upload file. Create the mcm-notes bucket first.')}}
async function loadContent(){const app=document.querySelector('#svl-content');if(!app)return;try{const classes=await assignedClasses(),mine=classes[0],notices=mine?await window.mcmDb.notices(mine.id):[],notes=mine?await window.mcmDb.notes(mine.id):[];app.innerHTML=`<div class="svl-content-head"><div><h2>Class Content</h2><p>Share notices and learning material with your assigned class.</p></div></div><form class="svl-content-form" onsubmit="saveSvlNotice(event)"><label>Class<select name="classId" required>${classes.map(c=>`<option value="${c.id}">${esc(c.name)} (${esc(c.code)})</option>`).join('')}</select></label><label>Notice title<input name="title" required placeholder="Assignment deadline update"></label><label>Message<textarea name="body" rows="4" required placeholder="Write notice for your students..."></textarea></label><button class="btn btn-primary" type="submit">Publish Notice</button></form><form class="svl-content-form upload-form" onsubmit="uploadSvlNote(event)"><h3>Upload Slides / Notes</h3><label>Class<select name="noteClass" required>${classes.map(c=>`<option value="${c.id}">${esc(c.name)} (${esc(c.code)})</option>`).join('')}</select></label><label>Material title<input name="noteTitle" required placeholder="Lecture 05 Slides"></label><label>Select file<input name="file" type="file" accept=".pdf,.ppt,.pptx,.doc,.docx,.zip" required></label><button class="btn btn-primary" type="submit">Upload Material</button></form><div class="svl-content-list"><h3>Recent Notices</h3>${notices.length?notices.map(n=>`<article><strong>${esc(n.title)}</strong><p>${esc(n.body)}</p><small>${new Date(n.created_at).toLocaleString()}</small></article>`).join(''):'<p class="muted">No notices published yet.</p>'}<h3>Uploaded Materials</h3>${notes.length?notes.map(n=>`<article><strong>${esc(n.title)}</strong><p><a href="${esc(n.file_url)}" target="_blank" rel="noopener">Open / download material</a></p></article>`).join(''):'<p class="muted">No materials uploaded yet.</p>'}</div>`}catch(err){app.innerHTML=`<p class="muted">${esc(err.message||'Connect Supabase to manage content.')}</p>`}}
window.saveSvlNotice=saveNotice;window.uploadSvlNote=uploadNote;window.loadSvlContent=loadContent;window.addEventListener('hashchange',()=>{if(location.hash==='#svl-dashboard')setTimeout(loadContent,150)});
})();